# Arduino Make file. Refer to https://github.com/sudar/Arduino-Makefile 

#BOARD_TAG    = atmega328 
BOARD_TAG    = uno
#ARDUINO_PORT = /dev/ttyUSB*
ARDUINO_PORT = /dev/ttyACM0
ARDUINO_LIBS = USB_Host_Shield_2_0 USB_Host_Shield_GPIO

include $(ARDMK_DIR)/arduino-mk/Arduino.mk
